### ISSUE TITLE
When signin-in, if you click on a field then click signup, an error pops up

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/PyMatcha#438]
https://streamable.com/dwc5z3

**Comment by supalarry** [comment]
This is far from perfect, but inputs use 3rd party validation library. The thing is that displaying error occurs before callback for clicking Sign up is called. If callback for sign up was called first, I could set a state that would prevent error from showing up. But since this is not the case, I don't want to spend too much time on something that's not essential. But overall I agree that what you are pointing out is true.
